### ISSUE TITLE
Doesn't work from outside a source tree

### ISSUE THREAD

**Issue by vmx** [ipfs-shipyard/package-table#5]
I've tried to run master from the source repository without installing it. I ran into an error as I was trying to pass in a `package-list.json` which is outside the current source directory:

```console
$ ./src/index.js --data=/home/vmx/src/pl/js-ipld-resolver/package-list.json
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/home/vmx/src/pl/package-table/home/vmx/src/pl/js-ipld-resolver/package-list.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/vmx/src/pl/package-table/src/index.js:14:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

Though it works when I'm within `/home/vmx/src/pl/package-table/home/vmx/src/pl/js-ipld-resolver` and call:

```console
$ /home/vmx/src/pl/package-table/src/index.js --data=./package-list.json
…
```

**Comment by ifstatic** [comment]
ok thank you

**Comment by achingbrain** [comment]
[Fixed](https://github.com/ipfs-shipyard/package-table/pull/42/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R23-R27) in #42
